=== thasim07/rest-apiautomation/src/test/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "description": {
      "type": "null"
    },
    "name": {
      "type": "string"
    },
    "name_with_namespace": {
      "type": "string"
    },
    "path": {
      "type": "string"
    },
    "path_with_namespace": {
      "type": "string"
    },
    "created_at": {
      "type": "string"
    },
    "default_branch": {
      "type": "string"
    },
    "tag_list": {
      "type": "array",
      "items": {}
    },
    "topics": {
      "type": "array",
      "items": {}
    },
    "ssh_url_to_repo": {
      "type": "string"
    },
    "http_url_to_repo": {
      "type": "string"
    },
    "web_url": {
      "type": "string"
    },
    "readme_url": {
      "type": "null"
    },
    "forks_count": {
      "type": "integer"
    },
    "avatar_url": {
      "type": "null"
    },
    "star_count": {
      "type": "integer"
    },
    "last_activity_at": {
      "type": "string"
    },
    "namespace": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "full_path": {
          "type": "string"
        },
        "parent_id": {
          "type": "null"
        },
        "avatar_url": {
          "type": "string"
        },
        "web_url": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "path",
        "kind",
        "full_path",
        "parent_id",
        "avatar_url",
        "web_url"
      ]
    },
    "container_registry_image_prefix": {
      "type": "string"
    },
    "_links": {
      "type": "object",
      "properties": {
        "self": {
          "type": "string"
        },
        "issues": {
          "type": "string"
        },
        "merge_requests": {
          "type": "string"
        },
        "repo_branches": {
          "type": "string"
        },
        "labels": {
          "type": "string"
        },
        "events": {
          "type": "string"
        },
        "members": {
          "type": "string"
        },
        "cluster_agents": {
          "type": "string"
        }
      },
      "required": [
        "self",
        "issues",
        "merge_requests",
        "repo_branches",
        "labels",
        "events",
        "members",
        "cluster_agents"
      ]
    },
    "code_suggestions": {
      "type": "boolean"
    },
    "packages_enabled": {
      "type": "boolean"
    },
    "empty_repo": {
      "type": "boolean"
    },
    "archived": {
      "type": "boolean"
    },
    "visibility": {
      "type": "string"
    },
    "owner": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "username": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "locked": {
          "type": "boolean"
        },
        "avatar_url": {
          "type": "string"
        },
        "web_url": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "username",
        "name",
        "state",
        "locked",
        "avatar_url",
        "web_url"
      ]
    },
    "resolve_outdated_diff_discussions": {
      "type": "boolean"
    },
    "container_expiration_policy": {
      "type": "object",
      "properties": {
        "cadence": {
          "type": "string"
        },
        "enabled": {
          "type": "boolean"
        },
        "keep_n": {
          "type": "integer"
        },
        "older_than": {
          "type": "string"
        },
        "name_regex": {
          "type": "string"
        },
        "name_regex_keep": {
          "type": "null"
        },
        "next_run_at": {
          "type": "string"
        }
      },
      "required": [
        "cadence",
        "enabled",
        "keep_n",
        "older_than",
        "name_regex",
        "name_regex_keep",
        "next_run_at"
      ]
    },
    "issues_enabled": {
      "type": "boolean"
    },
    "merge_requests_enabled": {
      "type": "boolean"
    },
    "wiki_enabled": {
      "type": "boolean"
    },
    "jobs_enabled": {
      "type": "boolean"
    },
    "snippets_enabled": {
      "type": "boolean"
    },
    "container_registry_enabled": {
      "type": "boolean"
    },
    "service_desk_enabled": {
      "type": "boolean"
    },
    "service_desk_address": {
      "type": "string"
    },
    "can_create_merge_request_in": {
      "type": "boolean"
    },
    "issues_access_level": {
      "type": "string"
    },
    "repository_access_level": {
      "type": "string"
    },
    "merge_requests_access_level": {
      "type": "string"
    },
    "forking_access_level": {
      "type": "string"
    },
    "wiki_access_level": {
      "type": "string"
    },
    "builds_access_level": {
      "type": "string"
    },
    "snippets_access_level": {
      "type": "string"
    },
    "pages_access_level": {
      "type": "string"
    },
    "analytics_access_level": {
      "type": "string"
    },
    "container_registry_access_level": {
      "type": "string"
    },
    "security_and_compliance_access_level": {
      "type": "string"
    },
    "releases_access_level": {
      "type": "string"
    },
    "environments_access_level": {
      "type": "string"
    },
    "feature_flags_access_level": {
      "type": "string"
    },
    "infrastructure_access_level": {
      "type": "string"
    },
    "monitor_access_level": {
      "type": "string"
    },
    "model_experiments_access_level": {
      "type": "string"
    },
    "model_registry_access_level": {
      "type": "string"
    },
    "emails_disabled": {
      "type": "boolean"
    },
    "emails_enabled": {
      "type": "boolean"
    },
    "shared_runners_enabled": {
      "type": "boolean"
    },
    "lfs_enabled": {
      "type": "boolean"
    },
    "creator_id": {
      "type": "integer"
    },
    "import_url": {
      "type": "null"
    },
    "import_type": {
      "type": "null"
    },
    "import_status": {
      "type": "string"
    },
    "import_error": {
      "type": "null"
    },
    "open_issues_count": {
      "type": "integer"
    },
    "description_html": {
      "type": "string"
    },
    "updated_at": {
      "type": "string"
    },
    "ci_default_git_depth": {
      "type": "integer"
    },
    "ci_forward_deployment_enabled": {
      "type": "boolean"
    },
    "ci_forward_deployment_rollback_allowed": {
      "type": "boolean"
    },
    "ci_job_token_scope_enabled": {
      "type": "boolean"
    },
    "ci_separated_caches": {
      "type": "boolean"
    },
    "ci_allow_fork_pipelines_to_run_in_parent_project": {
      "type": "boolean"
    },
    "build_git_strategy": {
      "type": "string"
    },
    "keep_latest_artifact": {
      "type": "boolean"
    },
    "restrict_user_defined_variables": {
      "type": "boolean"
    },
    "runners_token": {
      "type": "string"
    },
    "runner_token_expiration_interval": {
      "type": "null"
    },
    "group_runners_enabled": {
      "type": "boolean"
    },
    "auto_cancel_pending_pipelines": {
      "type": "string"
    },
    "build_timeout": {
      "type": "integer"
    },
    "auto_devops_enabled": {
      "type": "boolean"
    },
    "auto_devops_deploy_strategy": {
      "type": "string"
    },
    "ci_config_path": {
      "type": "string"
    },
    "public_jobs": {
      "type": "boolean"
    },
    "shared_with_groups": {
      "type": "array",
      "items": {}
    },
    "only_allow_merge_if_pipeline_succeeds": {
      "type": "boolean"
    },
    "allow_merge_on_skipped_pipeline": {
      "type": "null"
    },
    "request_access_enabled": {
      "type": "boolean"
    },
    "only_allow_merge_if_all_discussions_are_resolved": {
      "type": "boolean"
    },
    "remove_source_branch_after_merge": {
      "type": "boolean"
    },
    "printing_merge_request_link_enabled": {
      "type": "boolean"
    },
    "merge_method": {
      "type": "string"
    },
    "squash_option": {
      "type": "string"
    },
    "enforce_auth_checks_on_uploads": {
      "type": "boolean"
    },
    "suggestion_commit_message": {
      "type": "null"
    },
    "merge_commit_template": {
      "type": "null"
    },
    "squash_commit_template": {
      "type": "null"
    },
    "issue_branch_template": {
      "type": "null"
    },
    "autoclose_referenced_issues": {
      "type": "boolean"
    },
    "external_authorization_classification_label": {
      "type": "string"
    },
    "requirements_enabled": {
      "type": "boolean"
    },
    "requirements_access_level": {
      "type": "string"
    },
    "security_and_compliance_enabled": {
      "type": "boolean"
    },
    "compliance_frameworks": {
      "type": "array",
      "items": {}
    }
  },
  "required": [
    "id",
    "description",
    "name",
    "name_with_namespace",
    "path",
    "path_with_namespace",
    "created_at",
    "default_branch",
    "tag_list",
    "topics",
    "ssh_url_to_repo",
    "http_url_to_repo",
    "web_url",
    "readme_url",
    "forks_count",
    "avatar_url",
    "star_count",
    "last_activity_at",
    "namespace",
    "container_registry_image_prefix",
    "_links",
    "code_suggestions",
    "packages_enabled",
    "empty_repo",
    "archived",
    "visibility",
    "owner",
    "resolve_outdated_diff_discussions",
    "container_expiration_policy",
    "issues_enabled",
    "merge_requests_enabled",
    "wiki_enabled",
    "jobs_enabled",
    "snippets_enabled",
    "container_registry_enabled",
    "service_desk_enabled",
    "service_desk_address",
    "can_create_merge_request_in",
    "issues_access_level",
    "repository_access_level",
    "merge_requests_access_level",
    "forking_access_level",
    "wiki_access_level",
    "builds_access_level",
    "snippets_access_level",
    "pages_access_level",
    "analytics_access_level",
    "container_registry_access_level",
    "security_and_compliance_access_level",
    "releases_access_level",
    "environments_access_level",
    "feature_flags_access_level",
    "infrastructure_access_level",
    "monitor_access_level",
    "model_experiments_access_level",
    "model_registry_access_level",
    "emails_disabled",
    "emails_enabled",
    "shared_runners_enabled",
    "lfs_enabled",
    "creator_id",
    "import_url",
    "import_type",
    "import_status",
    "import_error",
    "open_issues_count",
    "description_html",
    "updated_at",
    "ci_default_git_depth",
    "ci_forward_deployment_enabled",
    "ci_forward_deployment_rollback_allowed",
    "ci_job_token_scope_enabled",
    "ci_separated_caches",
    "ci_allow_fork_pipelines_to_run_in_parent_project",
    "build_git_strategy",
    "keep_latest_artifact",
    "restrict_user_defined_variables",
    "runners_token",
    "runner_token_expiration_interval",
    "group_runners_enabled",
    "auto_cancel_pending_pipelines",
    "build_timeout",
    "auto_devops_enabled",
    "auto_devops_deploy_strategy",
    "ci_config_path",
    "public_jobs",
    "shared_with_groups",
    "only_allow_merge_if_pipeline_succeeds",
    "allow_merge_on_skipped_pipeline",
    "request_access_enabled",
    "only_allow_merge_if_all_discussions_are_resolved",
    "remove_source_branch_after_merge",
    "printing_merge_request_link_enabled",
    "merge_method",
    "squash_option",
    "enforce_auth_checks_on_uploads",
    "suggestion_commit_message",
    "merge_commit_template",
    "squash_commit_template",
    "issue_branch_template",
    "autoclose_referenced_issues",
    "external_authorization_classification_label",
    "requirements_enabled",
    "requirements_access_level",
    "security_and_compliance_enabled",
    "compliance_frameworks"
  ]
}

=== thasim07/rest-apiautomation/output/response.json
{"id":53081866,"description":null,"name":"callisto","name_with_namespace":"Mohamed Thasim / callisto","path":"callisto","path_with_namespace":"Thasim/callisto","created_at":"2023-12-15T05:02:08.928Z","default_branch":"main","tag_list":[],"topics":[],"ssh_url_to_repo":"git@gitlab.com:Thasim/callisto.git","http_url_to_repo":"https://gitlab.com/Thasim/callisto.git","web_url":"https://gitlab.com/Thasim/callisto","readme_url":null,"forks_count":0,"avatar_url":null,"star_count":0,"last_activity_at":"2023-12-15T05:02:08.928Z","namespace":{"id":79049517,"name":"Mohamed Thasim","path":"Thasim","kind":"user","full_path":"Thasim","parent_id":null,"avatar_url":"https://secure.gravatar.com/avatar/9a7fd6d3620a4a9d9de3bd55d5266887?s=80\u0026d=identicon","web_url":"https://gitlab.com/Thasim"},"container_registry_image_prefix":"registry.gitlab.com/thasim/callisto","_links":{"self":"https://gitlab.com/api/v4/projects/53081866","issues":"https://gitlab.com/api/v4/projects/53081866/issues","merge_requests":"https://gitlab.com/api/v4/projects/53081866/merge_requests","repo_branches":"https://gitlab.com/api/v4/projects/53081866/repository/branches","labels":"https://gitlab.com/api/v4/projects/53081866/labels","events":"https://gitlab.com/api/v4/projects/53081866/events","members":"https://gitlab.com/api/v4/projects/53081866/members","cluster_agents":"https://gitlab.com/api/v4/projects/53081866/cluster_agents"},"code_suggestions":true,"packages_enabled":true,"empty_repo":true,"archived":false,"visibility":"private","owner":{"id":19228764,"username":"Thasim","name":"Mohamed Thasim","state":"active","locked":false,"avatar_url":"https://secure.gravatar.com/avatar/9a7fd6d3620a4a9d9de3bd55d5266887?s=80\u0026d=identicon","web_url":"https://gitlab.com/Thasim"},"resolve_outdated_diff_discussions":false,"container_expiration_policy":{"cadence":"1d","enabled":false,"keep_n":10,"older_than":"90d","name_regex":".*","name_regex_keep":null,"next_run_at":"2023-12-16T05:02:08.967Z"},"issues_enabled":true,"merge_requests_enabled":true,"wiki_enabled":true,"jobs_enabled":true,"snippets_enabled":true,"container_registry_enabled":true,"service_desk_enabled":true,"service_desk_address":"contact-project+thasim-callisto-53081866-issue-@incoming.gitlab.com","can_create_merge_request_in":true,"issues_access_level":"enabled","repository_access_level":"enabled","merge_requests_access_level":"enabled","forking_access_level":"enabled","wiki_access_level":"enabled","builds_access_level":"enabled","snippets_access_level":"enabled","pages_access_level":"private","analytics_access_level":"enabled","container_registry_access_level":"enabled","security_and_compliance_access_level":"private","releases_access_level":"enabled","environments_access_level":"enabled","feature_flags_access_level":"enabled","infrastructure_access_level":"enabled","monitor_access_level":"enabled","model_experiments_access_level":"enabled","model_registry_access_level":"enabled","emails_disabled":false,"emails_enabled":true,"shared_runners_enabled":true,"lfs_enabled":true,"creator_id":19228764,"import_url":null,"import_type":null,"import_status":"none","import_error":null,"open_issues_count":0,"description_html":"","updated_at":"2023-12-15T05:02:08.928Z","ci_default_git_depth":20,"ci_forward_deployment_enabled":true,"ci_forward_deployment_rollback_allowed":true,"ci_job_token_scope_enabled":false,"ci_separated_caches":true,"ci_allow_fork_pipelines_to_run_in_parent_project":true,"build_git_strategy":"fetch","keep_latest_artifact":true,"restrict_user_defined_variables":false,"runners_token":"GR1348941eJr87Yy6rvgcPGEZxkjR","runner_token_expiration_interval":null,"group_runners_enabled":true,"auto_cancel_pending_pipelines":"enabled","build_timeout":3600,"auto_devops_enabled":false,"auto_devops_deploy_strategy":"continuous","ci_config_path":"","public_jobs":true,"shared_with_groups":[],"only_allow_merge_if_pipeline_succeeds":false,"allow_merge_on_skipped_pipeline":null,"request_access_enabled":true,"only_allow_merge_if_all_discussions_are_resolved":false,"remove_source_branch_after_merge":true,"printing_merge_request_link_enabled":true,"merge_method":"merge","squash_option":"default_off","enforce_auth_checks_on_uploads":true,"suggestion_commit_message":null,"merge_commit_template":null,"squash_commit_template":null,"issue_branch_template":null,"autoclose_referenced_issues":true,"external_authorization_classification_label":"","requirements_enabled":false,"requirements_access_level":"enabled","security_and_compliance_enabled":true,"compliance_frameworks":[]}
